# Generated by Django 5.0 on 2024-10-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testeCursos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='topics',
            new_name='Topic',
        ),
    ]
